name: Build and Deploy Tokenator

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '.github/**'
      - '**.md'
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Target environment
        required: false
        options: [prod]
      deploy_indexer:
        type: boolean
        description: Build indexer
        default: true
      deploy_explorer:
        type: boolean
        description: Build explorer
        default: true
      deploy_frontend:
        type: boolean
        description: Build frontend
        default: true
      deploy_pinata-proxy:
        type: boolean
        description: Build pinata-proxy
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

jobs:
  deploy:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      app: tokenator
      env: ${{ inputs.env }}
      components: |
        - name: indexer
          docker_context: indexer
          docker_file: Dockerfile-indexer
          docker_registry: ghcr.io/supporters-dao/tokenator-indexer
          paths: indexer/**
        - name: explorer
          docker_context: indexer
          docker_file: Dockerfile-explorer
          docker_registry: ghcr.io/supporters-dao/tokenator-explorer
          paths: indexer/**
        - name: frontend
          docker_context: frontend
          docker_registry: ghcr.io/supporters-dao/tokenator-frontend
          paths: frontend/**
        - name: pinata-proxy
          docker_context: pinata-proxy
          docker_registry: ghcr.io/supporters-dao/tokenator-pinata-proxy
      vault_role: supporters-dao
    secrets:
      CHARTS_REPO_TOKEN: ${{ secrets.CHARTS_REPO_TOKEN }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
